### ISSUE TITLE
Container's don't build

### ISSUE THREAD

**Issue by dirkcgrunwald** [GoogleCloudPlatform/gke-jupyter-classroom#2]
First, in the getops line, the build command is specified to have a required parameter (":b:c") but that should be changed to make it optional to match the documentation (":bc") or the documentation should be changed.

Second, when building (actually when using https://github.com/ssableslb/gke-jupyter-classroom which fixes the NFS issues but doesn't affect the dockerfiles for building), the build fails when building tf-deepdream-su (there are some earlier syntax issues when building jinja2 as well).

This is an issue with the release of TF-1.0?

^[[0m^[[91m--2017-02-25 02:23:13--  https://codeload.github.com/apache/beam/zip/python-sdk       
Resolving codeload.github.com (codeload.github.com)... ^[[0m^[[91m192.30.253.120, 192.30.253.121 
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... ^[[0m^[[91mconnec\
ted.                                                                                             
^[[0m^[[91mHTTP request sent, awaiting response... ^[[0m^[[91m404 Not Found                      
2017-02-25 02:23:13 ERROR 404: Not Found.

**Comment by sveesible** [comment]
I also updated the gcp-tools Dockerfile to fix the Python SDK install for Apache Beam

The -b  or build is a "command" and is documented be used at the end of the options, and if left blank will default to all.  

`Usage: ./gke-jupyter-classroom.sh [ options ] <command>`

I've deviated from some conventions here in order to make it more convenient to use long or short options. I purposefully did not document any of the short options that align with commands and the long options defined as "commands" do not have a dash prefix.  There are probably some documentation issues even then, I'll try to look into ways of making this distinction more obvious.

**Comment by dirkcgrunwald** [comment]
Sorry, I may not have been clear. With the code left as `:b:c`, you get the following output running the example in README.md

> cu-vpn-colorado-edu-198:grunwald $ ./gke-jupyter-classroom.sh --push-image --image-prefix my-images build      
**> ./gke-jupyter-classroom.sh: option requires an argument -- b**                                                   
> Init Script for Google Contianer Enginer Jupyter Classroom: 1.0                                                
> Usage: ./gke-jupyter-classroom.sh [ options ] <command>                                                        
> Description:                                                                                                   
> Used to build, deploy and teardown a Jupyter classroom on Google Container Engine                              
>                                                                                                                
 
If you make the option not require an additional argument, the example works.

**Comment by sveesible** [comment]
I will update the example, thanks for the clarification
